### ISSUE TITLE
convert persian date to hijri

### ISSUE THREAD

**Issue by mohamadjavadx** [persian-calendar/calendar#1]
hello, how to convert persian date to hijri using this lib

**Comment by ebraminio** [comment]
سلام گرامی یک چنین چیزی نیازی خواهید داشت
 
```
val date = IslamicDate(PersianDate(1398, 1, 1))
// date.year, date.month, date.dayOfMonth
```

البته اگر از این کتابخانه استفاده می‌کنید نیاز است از مجوز جی‌پی‌ال استفاده کنید چون ما هم از کدهای جی‌پی‌الی در آن استفاده کردیم که ما را مجبور به آن کرده است

https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

به نظر که پروژهٔ جالبی شروع کرده‌اید، موفق باشید :)

**Comment by mohamadjavadx** [comment]
سلام ممنون ، اگر فرصتی بود و ادامه دادم پروژه رو چشم حتما
